//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyTurismo_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoTurismoEntities : DbContext
    {
        public ProyectoTurismoEntities()
            : base("name=ProyectoTurismoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Alojamiento> Tb_Alojamiento { get; set; }
        public virtual DbSet<Tb_Categoria> Tb_Categoria { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Empleado> Tb_Empleado { get; set; }
        public virtual DbSet<Tb_Factura> Tb_Factura { get; set; }
        public virtual DbSet<Tb_Reserva> Tb_Reserva { get; set; }
        public virtual DbSet<Tb_Tour> Tb_Tour { get; set; }
        public virtual DbSet<Tb_Transporte> Tb_Transporte { get; set; }
        public virtual DbSet<Tb_Ubicacion> Tb_Ubicacion { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<vw_Factura_reservas_basicas> vw_Factura_reservas_basicas { get; set; }
    
        public virtual ObjectResult<usp_ListarClientesConFacturas_DesdeVista_Result> usp_ListarClientesConFacturas_DesdeVista(Nullable<int> codCli, string estadoFactura)
        {
            var codCliParameter = codCli.HasValue ?
                new ObjectParameter("CodCli", codCli) :
                new ObjectParameter("CodCli", typeof(int));
    
            var estadoFacturaParameter = estadoFactura != null ?
                new ObjectParameter("EstadoFactura", estadoFactura) :
                new ObjectParameter("EstadoFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarClientesConFacturas_DesdeVista_Result>("usp_ListarClientesConFacturas_DesdeVista", codCliParameter, estadoFacturaParameter);
        }
    }
}
