
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyTurismo_ADO
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Categoria
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_Categoria()
    {

        this.Tb_Alojamiento = new HashSet<Tb_Alojamiento>();

    }


    public int ID_Categoria { get; set; }

    public string Des_Cat { get; set; }

    public decimal Tar_Por_Noc { get; set; }

    public string Caracteristicas { get; set; }

    public byte[] Foto { get; set; }

    public string Usu_Reg { get; set; }

    public Nullable<System.DateTime> Fec_Reg { get; set; }

    public string Usu_ult_Mod { get; set; }

    public Nullable<System.DateTime> Fec_ult_mod { get; set; }

    public string Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Alojamiento> Tb_Alojamiento { get; set; }

}

}
