//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyTurismo_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cliente()
        {
            this.Tb_Alojamiento = new HashSet<Tb_Alojamiento>();
            this.Tb_Reserva = new HashSet<Tb_Reserva>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nom_Cli { get; set; }
        public string Ape_Cli { get; set; }
        public string Dni_Cli { get; set; }
        public string Num_Tel { get; set; }
        public string Email_Cli { get; set; }
        public Nullable<System.DateTime> Fec_Nac { get; set; }
        public string Sex_Cli { get; set; }
        public string Usu_Reg { get; set; }
        public Nullable<System.DateTime> Fec_Reg { get; set; }
        public string Usu_ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_ult_mod { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Alojamiento> Tb_Alojamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Reserva> Tb_Reserva { get; set; }
    }
}
