
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyTurismo_ADO
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Empleado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_Empleado()
    {

        this.Tb_Tour = new HashSet<Tb_Tour>();

        this.Tb_Transporte = new HashSet<Tb_Transporte>();

        this.Tb_Empleado1 = new HashSet<Tb_Empleado>();

    }


    public int ID_Empleado { get; set; }

    public string Nom_Emp { get; set; }

    public string Ape_Emp { get; set; }

    public string Dni_Emp { get; set; }

    public string Tel_Emp { get; set; }

    public string Email_Emp { get; set; }

    public string Rol_Emp { get; set; }

    public Nullable<int> Supervisor_ID { get; set; }

    public string Usu_Reg { get; set; }

    public Nullable<System.DateTime> Fec_Reg { get; set; }

    public string Usu_ult_Mod { get; set; }

    public Nullable<System.DateTime> Fec_ult_mod { get; set; }

    public string Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Tour> Tb_Tour { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Transporte> Tb_Transporte { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Empleado> Tb_Empleado1 { get; set; }

    public virtual Tb_Empleado Tb_Empleado2 { get; set; }

}

}
