
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyTurismo_ADO
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Factura
{

    public int ID_Factura { get; set; }

    public int ID_Reserva { get; set; }

    public System.DateTime Fec_Emi { get; set; }

    public decimal Total { get; set; }

    public Nullable<int> Met_Pag { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaActualizacion { get; set; }

    public string Auditoria { get; set; }



    public virtual Tb_Reserva Tb_Reserva { get; set; }

}

}
