
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyTurismo_ADO
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Reserva
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_Reserva()
    {

        this.Tb_Factura = new HashSet<Tb_Factura>();

    }


    public int ID_Reserva { get; set; }

    public int ID_Cliente { get; set; }

    public int ID_Tour { get; set; }

    public System.DateTime Fec_Res { get; set; }

    public string Usu_Reg { get; set; }

    public Nullable<System.DateTime> Fec_Reg { get; set; }

    public string Usu_ult_Mod { get; set; }

    public Nullable<System.DateTime> Fec_ult_mod { get; set; }

    public string Estado { get; set; }



    public virtual Tb_Cliente Tb_Cliente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Factura> Tb_Factura { get; set; }

    public virtual Tb_Tour Tb_Tour { get; set; }

}

}
